[tool.poetry]
name = "jira-utils"
version = "0.1.0"
description = ""
authors = ["Ivan Lopez Rodriguez <ivanlrodr@ext.inditex.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
jira = "^3.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
